services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-study
    restart: always
    ports:
      - "8081:80" # Мы вешаем его на порт 8081, чтобы не занимать основной 80-й
    environment:
      PMA_HOST: db # Указываем имя сервиса базы данных, к которой подключаемся
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - shared

  prisma:
    build: ./prisma
    container_name: prisma-studio
    restart: always
    env_file:
      - ./prisma/.env
    ports:
      - "5555:5555"
    volumes:
      - ./prisma:/app
      # МАГИЯ: этот пустой путь говорит Docker:
      # "Используй node_modules из образа, а не из локальной папки"
      - /app/node_modules
    networks:
      - shared

volumes:
  mysql-study-data:

networks:
  shared:
    name: mysql-shared
