services:
  db:
    image: mysql:8.0
    container_name: mysql-lab01
    restart: always
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lab
    ports:
      - "3307:3306" # different port per lab — avoids conflicts if multiple labs run
    volumes:
      - lab01-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # ← points at THIS lab's file
    networks:
      - shared

volumes:
  lab01-data: # isolated volume — won't interfere with other labs

networks:
  shared:
    external: true # tells Docker: don't create this, it already exists, at the root
    name: mysql-shared # must match exactly what root compose defined
